#!/usr/bin/env python
from modules.app.cli import App
from modules.compose.cli import Compose
import fire


class Composer(object):
    def __init__(self):
        self.app = App()
        self.compose = Compose()


if __name__ == '__main__':
    fire.Fire(Composer)
